# Generated by Django 2.1.7 on 2019-03-19 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='物品名')),
                ('course', models.CharField(max_length=40, verbose_name='使用人')),
                ('num', models.CharField(max_length=30, verbose_name='使用数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='借阅时间')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
        ),
    ]
