# Generated by Django 2.1.7 on 2019-03-19 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='物品名')),
                ('desc', models.CharField(max_length=300, verbose_name='物品描述')),
                ('detail', models.TextField(verbose_name='物品详情')),
                ('students', models.IntegerField(default=0, verbose_name='使用人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='剩余数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '物品',
                'verbose_name_plural': '物品',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=30, verbose_name='使用数量')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='借阅时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='使用人')),
            ],
            options={
                'verbose_name': '使用者',
                'verbose_name_plural': '使用者',
            },
        ),
    ]
