# Generated by Django 2.1.7 on 2019-03-19 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190319_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
